FishCointaiment:
  required:
    - id
    - type
  allOf:
    - $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/Common
  type: object
  description: ''
  properties:
    address:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/schema.org.yaml#/address
    alternateName:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    areaServed:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    category:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        - type: string
          enum:
            - TBD
    dataProvider:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    description:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/description
    endpoint:
      x-ngsi:
        type: Property
        model: 'https://schema.org/URL'
      type: string
      description: ''
      format: uri
    location:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/location
    name:
      $ref: >-
        https://raw.githubusercontent.com/smart-data-models/data-models/master/ngsi-ld.yaml#/name
    owner:
      x-ngsi:
        type: Property
      type: array
      description: ''
      items:
        anyOf:
          - type: string
            minLength: 1
            maxLength: 256
            pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
          - type: string
            format: uri
    relatedSource:
      x-ngsi:
        type: Property
      type: array
      description: List of IDs the current entity may have in external applications
      items:
        - type: object
          values:
            application:
              anyOf:
                - type: string
                  minLength: 1
                  maxLength: 256
                  pattern: '^[\w\-\.\{\}\$\+\*\[\]`|~^@!,:\\]+$'
                - type: string
                  format: uri
            applicationEntityId:
              type: string
    source:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
    version:
      x-ngsi:
        type: Property
        model: 'https://schema.org/Text'
      type: string
      description: ''
